---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets-controller
  namespace: argocd
  annotations: {argocd.argoproj.io/sync-wave: "-15"}
spec:
  project: security
  sources:
    - repoURL: https://bitnami.github.io/sealed-secrets
      chart: sealed-secrets
      targetRevision: 2.19.0
      helm:
        releaseName: sealed-secrets
        valueFiles: [$values/platform/management/sealed-secrets/values.yaml]
    - repoURL: https://github.com/kaycee1771/verda-platform-takehome.git
      targetRevision: main
      ref: values
  destination: {server: https://kubernetes.default.svc, namespace: sealed-secrets}
  syncPolicy:
    automated: {prune: false, selfHeal: true, allowEmpty: false}
    syncOptions: [ServerSideApply=true, PruneLast=true]
