---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: harbor-staging
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  secretName: {{ .Values.certificate.stagingSecretName | quote }}
  revisionHistoryLimit: 3
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always
  dnsNames:
    - {{ include "verdaHarbor.hostname" . | quote }}
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: harbor-letsencrypt-staging
{{- if .Values.gates.stagingCertificateVerified }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: harbor-production
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
    verda.platform/staging-proof: verified
spec:
  secretName: {{ .Values.certificate.productionSecretName | quote }}
  revisionHistoryLimit: 3
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always
  dnsNames:
    - {{ include "verdaHarbor.hostname" . | quote }}
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: harbor-letsencrypt-production
{{- end }}
