---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor-postgresql
  namespace: argocd
  annotations: {argocd.argoproj.io/sync-wave: "-8"}
spec:
  project: registry
  source:
    repoURL: https://github.com/kaycee1771/verda-platform-takehome.git
    targetRevision: main
    path: platform/management/harbor/postgresql
    helm: {releaseName: harbor-postgresql}
  destination: {server: https://kubernetes.default.svc, namespace: harbor}
  syncPolicy:
    automated: {prune: false, selfHeal: true, allowEmpty: false}
    syncOptions: [PruneLast=true]
