---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno-monitoring
  namespace: argocd
  annotations: {argocd.argoproj.io/sync-wave: "-2"}
spec:
  project: security
  source:
    repoURL: https://github.com/kaycee1771/verda-platform-takehome.git
    targetRevision: main
    path: platform/management/kyverno/monitoring
  destination: {server: https://kubernetes.default.svc, namespace: kyverno}
  syncPolicy:
    automated: {prune: true, selfHeal: true, allowEmpty: false}
    syncOptions: [SkipDryRunOnMissingResource=true, PruneLast=true]
