---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  annotations: {argocd.argoproj.io/sync-wave: "-6"}
spec:
  project: observability
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: loki
      targetRevision: 7.3.0
      helm:
        releaseName: loki
        valueFiles: [$values/platform/management/loki/values.yaml]
    - repoURL: https://github.com/kaycee1771/verda-platform-takehome.git
      targetRevision: main
      ref: values
  destination: {server: https://kubernetes.default.svc, namespace: loki}
  syncPolicy:
    automated: {prune: false, selfHeal: true, allowEmpty: false}
    syncOptions: [ServerSideApply=true, PruneLast=true]
