---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rancher
  namespace: argocd
  annotations: {argocd.argoproj.io/sync-wave: "-10"}
spec:
  project: management
  source:
    repoURL: https://github.com/kaycee1771/verda-platform-takehome.git
    targetRevision: main
    path: platform/management/rancher
    helm: {releaseName: rancher}
  destination: {server: https://kubernetes.default.svc, namespace: cattle-system}
  syncPolicy:
    automated: {prune: false, selfHeal: true, allowEmpty: false}
    syncOptions: [ServerSideApply=true, PruneLast=true]
