{{- if .Values.enabled }}
{{- $admission := include "verdaHarborPostgresql.assertAdmission" . -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: harbor-postgresql
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "verdaHarborPostgresql.labels" . | nindent 4 }}
  annotations:
    verda.platform/admission: {{ $admission | quote }}
automountServiceAccountToken: false
{{- end }}
