---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: foundation
  namespace: argocd
spec:
  description: Namespace, priority, quota, and baseline isolation ownership
  sourceRepos:
    - https://github.com/kaycee1771/verda-platform-takehome.git
  destinations:
    - {namespace: argocd, server: https://kubernetes.default.svc}
    - {namespace: demo-dev, server: https://kubernetes.default.svc}
    - {namespace: demo-staging, server: https://kubernetes.default.svc}
    - {namespace: demo-prod, server: https://kubernetes.default.svc}
    - {namespace: sealed-secrets, server: https://kubernetes.default.svc}
    - {namespace: kyverno, server: https://kubernetes.default.svc}
    - {namespace: cattle-system, server: https://kubernetes.default.svc}
    - {namespace: harbor, server: https://kubernetes.default.svc}
    - {namespace: monitoring, server: https://kubernetes.default.svc}
    - {namespace: loki, server: https://kubernetes.default.svc}
    - {namespace: logging, server: https://kubernetes.default.svc}
  clusterResourceWhitelist:
    - {group: "", kind: Namespace}
    - {group: scheduling.k8s.io, kind: PriorityClass}
  namespaceResourceWhitelist:
    - {group: bitnami.com, kind: SealedSecret}
    - {group: "", kind: LimitRange}
    - {group: "", kind: ResourceQuota}
    - {group: "", kind: ServiceAccount}
    - {group: networking.k8s.io, kind: NetworkPolicy}
    - {group: rbac.authorization.k8s.io, kind: Role}
    - {group: rbac.authorization.k8s.io, kind: RoleBinding}
  orphanedResources: {warn: true}
