---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: management
  namespace: argocd
spec:
  description: Phase 6 Rancher management-plane trust domain
  sourceRepos:
    - https://github.com/kaycee1771/verda-platform-takehome.git
    - https://releases.rancher.com/server-charts/stable
  destinations:
    - {namespace: cattle-system, server: https://kubernetes.default.svc}
  clusterResourceWhitelist:
    - {group: "", kind: Namespace}
    - {group: apiextensions.k8s.io, kind: CustomResourceDefinition}
    - {group: admissionregistration.k8s.io, kind: MutatingWebhookConfiguration}
    - {group: admissionregistration.k8s.io, kind: ValidatingWebhookConfiguration}
    - {group: rbac.authorization.k8s.io, kind: ClusterRole}
    - {group: rbac.authorization.k8s.io, kind: ClusterRoleBinding}
  namespaceResourceWhitelist:
    - {group: "*", kind: "*"}
  orphanedResources: {warn: true}
