---
environment: prod
namespace: demo-prod
replicas: 2
hostname: platform-prod.95-133-252-214.nip.io
priorityClassName: platform-workload
serviceAccountName: platform-demo
imagePullSecretName: platform-demo-registry
activation: {enabled: true, imageDigestLocked: true, pullSecretReady: true, serviceMonitorCRDReady: true}
certificate:
  bootstrapEnabled: true
  stagingCertificateVerified: true
  acmeEmail: kelechi.okpala13@yahoo.com
  ingressClassName: traefik
  stagingSecretName: platform-demo-staging-tls
  productionSecretName: platform-demo-tls
image:
  repository: harbor.95-133-252-214.nip.io/platform-demo/platform-demo
  digest: sha256:1d48d05c8d4945fd891b07a865fcbdc7af459fa77adb75f9a88fd8ee0bfb289d
  pullPolicy: IfNotPresent
resources:
  requests: {cpu: 10m, memory: 16Mi}
  limits: {cpu: 100m, memory: 64Mi}
