{{- if .Values.rancher.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: rancher-ingress
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  podSelector:
    matchLabels:
      app: rancher
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              app.kubernetes.io/name: rke2-traefik
      ports:
        - protocol: TCP
          port: 80
    - from:
        - podSelector: {}
      ports:
        - {protocol: TCP, port: 80}
        - {protocol: TCP, port: 443}
        - {protocol: TCP, port: 444}
        - {protocol: TCP, port: 6666}
{{- end }}
