---
apiVersion: v1
kind: ResourceQuota
metadata: {name: stage-a-budget, namespace: demo-prod}
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 2Gi
    limits.cpu: "4"
    limits.memory: 4Gi
    pods: "16"
    persistentvolumeclaims: "2"
