---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: platform-demo-registry
  namespace: demo-prod
  annotations:
    sealedsecrets.bitnami.com/strict: "true"
spec:
  encryptedData:
    .dockerconfigjson: REQUIRED_SEALED_CIPHERTEXT_DEMO_PROD_REGISTRY
  template:
    metadata: {name: platform-demo-registry, namespace: demo-prod}
    type: kubernetes.io/dockerconfigjson
