---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-project
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  project: platform-bootstrap
  source:
    repoURL: https://github.com/kaycee1771/verda-platform-takehome.git
    targetRevision: main
    path: gitops/appprojects
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff: {duration: 5s, factor: 2, maxDuration: 3m}
