---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-staging
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-11"
spec:
  secretName: {{ .Values.certificateSecretName | quote }}
  revisionHistoryLimit: 3
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always
  dnsNames:
    - {{ include "verdaCertStaging.hostname" . | quote }}
  usages:
    - digital signature
    - server auth
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: letsencrypt-staging
