---
- name: Prepare management hosts for a future RKE2 CIS-profile installation
  hosts: management_servers
  order: inventory
  serial: 1
  become: true
  gather_facts: true
  any_errors_fatal: true
  roles:
    - role: common
    - role: hardening
    - role: storage_device
